travis:
  secure:
    BINSTAR_TOKEN: ULxBQO5qMgnYXB8fkohjx9ElRfjA3cd0W5IdhrwfDijsiBv/MXo0r1Qss80VD6LkVJLmzPIjuv+isRKo7h2zBDWLRqbHG8G98/QY0Qa0Ca8DrZzlhsEH3AxzzeEVd0UM2EtTclSarJMcyeXquqP7TlHKsYxlPydT6wW9fDtx1XWVCAwE4rco/Cz3LUfIkylNz8YAE3H+BAxO4ez4lzNV/GdXhCdpZX38A0QRxWTpdAfXHkPJWYVxy8ov3xxe2wSkqieIRg5ufhWXfHo7IK7nIPauNNwbnD3QhEL1OR2HXByD9KJN7Nzd6F3PSol6ODxvtxgrznjVMUWgI8BK8NnnvDZfUQvEQjbAknM3ZSkeJ7psj2A3YPOlykWAQHSPMkQdZU71X519dDk0QrPbl1bYkSK/5lcgRehnCAdfb5Ons9brPx4BSu29ZRvT4kEtTBRzoU8lESc25Fhmy44DGXHEyXXG2ZOrEfbCuuSXkpwrgMmizXKHiifzM9So4FFHCPhwFvk8QLUAjYermoY93QluP/INCKl2YnLhMBIaWsrozHttbE4xlq6LlNgGI+lThR45O/MSLyu3wGrwukMUVslEJh8N9Fo1btiVsKMqfnT/kmGU6Slu9/p8a8FP/kWu7XlQ03ObBmHNjtYX1Tiaz3jIdcGkI2cgXhgKDuSJMJrRc30=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
